// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDILgYXJ55G-p0cBTtrwSgPOSp9av3gp78',
    appId: '1:239735387726:web:c95d30fa44d7448dd8751f',
    messagingSenderId: '239735387726',
    projectId: 'flutter-project-4b285',
    authDomain: 'flutter-project-4b285.firebaseapp.com',
    storageBucket: 'flutter-project-4b285.firebasestorage.app',
    measurementId: 'G-4M2SWQ7MQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5FMpJ6S8myEGUSlHR-8fanqJAreAyQT8',
    appId: '1:239735387726:android:e19207ce8df19f14d8751f',
    messagingSenderId: '239735387726',
    projectId: 'flutter-project-4b285',
    storageBucket: 'flutter-project-4b285.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFrRFBTGXZkMJULL_328NClfBWRR-MuME',
    appId: '1:239735387726:ios:3c9ef1ab1f8480e8d8751f',
    messagingSenderId: '239735387726',
    projectId: 'flutter-project-4b285',
    storageBucket: 'flutter-project-4b285.firebasestorage.app',
    iosBundleId: 'com.example.dxproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFrRFBTGXZkMJULL_328NClfBWRR-MuME',
    appId: '1:239735387726:ios:3c9ef1ab1f8480e8d8751f',
    messagingSenderId: '239735387726',
    projectId: 'flutter-project-4b285',
    storageBucket: 'flutter-project-4b285.firebasestorage.app',
    iosBundleId: 'com.example.dxproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDILgYXJ55G-p0cBTtrwSgPOSp9av3gp78',
    appId: '1:239735387726:web:947f2dbbde3b73bed8751f',
    messagingSenderId: '239735387726',
    projectId: 'flutter-project-4b285',
    authDomain: 'flutter-project-4b285.firebaseapp.com',
    storageBucket: 'flutter-project-4b285.firebasestorage.app',
    measurementId: 'G-6L7VZ3LM6T',
  );

}